### PR TITLE
Enable LFS

### PR DESCRIPTION
**Pull request by purplg**
I had to enable this when I used this template. I don't think there's a reason to not enable it by default. I used these changes in [my Bevy Jam 4 submission](https://github.com/purplg/flock-flow)

Thanks

### CODE REVIEW

**Review by alice-i-cecile — COMMENTED** [review]
My concern with turning this on is that Github is very stingy with LFS bandwidth, especially for private repos. Did you run into that?

**Comment by purplg** [comment]
> My concern with turning this on is that Github is very stingy with LFS bandwidth, especially for private repos. Did you run into that?

No, I didn't run into any issues with that. I ran all the release jobs probably around 5 or more times the last few days, so not an excessive amount. My assets are rather small too. I wasn't aware of the stingyness.

**Comment by mockersf** [comment]
Without paying for more, you can have 1GB of data in git Las, and 1GB per month of bandwidth. People cloning your repo counts against that quota.

does enabling ifs on checkout on a repo without ifs enabled have any side effect?

**Comment by purplg** [comment]
Alternatively, maybe an env var can be added at the top, alongside `binary` and `add_binaries_to_github_release`, which defaults to false to easily enable LFS for all the targets.

**Comment by purplg** [comment]
I made the change and gave it a quick test on a simple hello world repo [here](https://github.com/purplg/test-bevy-ci). There's 2 releases, one with LFS disabled where the png is a pointer file and the other with LFS enabled where the asset is binary, as expected.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by mockersf** [comment]
could you add a disclaimer to really look at GitHub pricing for lfs before thinking about using it? with a link to https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage

**Comment by purplg** [comment]
@mockersf Thanks, definitely a good idea. I've updated the branch.

Turns out, GitHub has a feature to show "note", and other, blocks which is perfect for this. I've chosen "warning". Please let me know if you think a different level is better.

**Review by alice-i-cecile — APPROVED** [review]
Great choice. Agreed on warning. I might even strengthen the warning: the storage is unusually expensive at game scales.

**Comment by purplg** [comment]
> I might even strengthen the warning: the storage is unusually expensive at game scales.

Maybe, but as I understand it, enabling this option doesn't necessarily increase quota usage directly, but rather just enable LFS within the pipelines (so the pointer files are resolved). I made a few mistakes enabling this myself, which cost me workflow minutes, and eventually money as I ran out of the allotted free workflow time. So I wanted to contribute this back in hopes it'd save others from my mistakes.

But I still think the "warning" is warranted as to not provide some false sense of security around LFS and to encourage the user to understand and decide for them self.

**Review by mockersf — APPROVED** [review]

**Pull request merged**
