### PR TITLE
changing toolchain from action-rs to dtolnay

### PR DESCRIPTION
**Pull request by vital14**
Changing into script the references to action-rs toolchain that is not updating, and using dtolnay version
#18

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
On board with this idea. Ping me if I forget to keep approving CI here please.

**Review by alice-i-cecile — APPROVED** [review]

**Review by mockersf — CHANGES_REQUESTED** [review]
you didn't change the action parameters. You should remove the toolchain, profile, components or override parameters

**Comment by vital14** [comment]
@alice-i-cecile could you please approve the ci to run this changes?

**Comment by alice-i-cecile** [comment]
image

Nothing is attempting to run, from what I can see 🤔

**Comment by mockersf** [comment]
your workflow definition is not valid: https://github.com/bevyengine/bevy_github_ci_template/actions/runs/4055140985

**Comment by alice-i-cecile** [comment]
Ping @vital14, I'd like to fix this up for the upcoming Jam :)

**Comment by mockersf** [comment]
done in #29

**Pull request closed without merging**
