### PR TITLE
Add a workflow for publishing to itch.io

### PR DESCRIPTION
**Pull request by idanarye**

### CODE REVIEW

**Comment by mockersf** [comment]
Do you have an opinion on using https://github.com/marketplace/actions/butler-push instead of doing it manually?

Would it be possible to reuse the builds uploaded to the release tag instead of rebuilding?

**Comment by idanarye** [comment]
> Do you have an opinion on using https://github.com/marketplace/actions/butler-push instead of doing it manually?

AFAIK if we use the action we'll have to write it separately for each channel. By doing it manually, I can use a `for` loop.

There is always an option of using a matrix, but this seems... wasteful?

> Would it be possible to reuse the builds uploaded to the release tag instead of rebuilding?

Actually in my usecase I was not rebuilding because I was not using the release tag at all - I ran only this workflow. itch.io was my distribution platform, not GitHub.

If we want to tie this to the tag release workflow, then I think it would be too cumbersome to make the user trigger this from the GitHub UI, since they'll have to wait for the release to finish before doing so and since they'll have to manually pick the tag from the combobox. Instead, I think it'd be better to add another job to `release.yaml` and making it not run if the user did not set `env.itch_target`.

If we do that, we can also use the tag name for `butler`'s `--userversion` flag.

**Comment by mockersf** [comment]
> Instead, I think it'd be better to add another job to `release.yaml` and making it not run if the user did not set `env.itch_target`.

I think I would prefer that. You could also add a env variable to disable deploying to GitHub release if you want?

**Comment by idanarye** [comment]
> You could also add a env variable to disable deploying to GitHub release if you want?

This would mean the regular release cycle will have to use artifacts in addition to deploying to the GitHub release. I'm... not sure I see the advantage in that.

**Comment by alice-i-cecile** [comment]
Closed in favor of #13.

**Pull request closed without merging**
