### PR TITLE
Document how to get around "Resource not accessible" error in Github actions

### LINKED ISSUE #26: Github Actions: "Error: Resource not accessible by integration"
When testing using this template for the Bevy 0.10 upgrade (see #25) I ran into an error with the Github actions:
`Resource not accessible by integration`
You can see [the attempt here](https://github.com/paul-hansen/bevy_github_ci_template_test/actions/runs/4393538939/jobs/7694003889).

To fix this I had to go to my repo's `settings -> actions -> general` and enable read and write permissions for the workflows near the bottom of the page, then re-running the actions worked perfectly
image

I think we'll probably want to add something to the README about this? It wasn't obvious what the solution was and took some searching and ended up guessing on where to look for something to enable write permissions.

### PR DESCRIPTION
**Pull request by paul-hansen**
Fixes #26

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by rparrett** [comment]
Should we be specifying the required permissions in the workflow instead?

This seems sort of new / I don't remember having to do this previously.

https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token

**Comment by rparrett** [comment]
Is it possible that this was only required because it was being tested in a fork?

**Comment by paul-hansen** [comment]
> Is it possible that this was only required because it was being tested in a fork?

I think it's likely that it is because it's a fork but I created it using the big green "Use this template" button on GitHub so it's pretty likely that others would run into it too. 
image


> This seems sort of new / I don't remember having to do this previously.

It could also be a recent thing, though this is my first time using it as a template. When I used this for the bevy jam 2, I added it to an existing project and I didn't run into it then.

> Should we be specifying the required permissions in the workflow instead?

If that's possible that would be ideal! Didn't know that might be a thing when I wrote this PR.

**Comment by rparrett** [comment]
> It could also be a recent thing, though this is my first time using it as a template. 

Good point. Actually, I haven't tested this as a template before, but I can confirm that I see the same thing when using the "Use this template" button.

It seems like this might be an old issue with `actions-rs/clippy-check` though.

https://github.com/actions-rs/clippy-check/issues/2

**Comment by rparrett** [comment]
Pinging @mockersf for github CI expertise. Is it an issue to instruct users to add these permissions?

They don't seem to be the default even for non-forked repos.

This also seems to be a problem with the release workflow, so moving away from `actions-rs/clippy-check` doesn't seem like a solution.

**Review by Vrixyz — APPROVED** [review]

**Pull request merged**
