### PR TITLE
Add triple license, CC0 or MIT or Apache2.0

### LINKED ISSUE #10: Update the licenses like bevy repo did
I'm basing my jam game off of this and wanted to include licenses.
I noticed that bevy repo updated their format (file per license), while this repo uses the old one (short file with external links).

### PR DESCRIPTION
**Pull request by ameknite**
Similar to #23 

Fixes #10 and #4

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by mockersf** [comment]
I'm not sure this fixes #4, but then I still don't know how to licence the template with MIT/Apache2 and let users relicense their project how they want. I think their project would qualify as derivative work and mean they have to use a compatible license.

Maybe relicensing the template as public domain or CC-0?

**Comment by ameknite** [comment]
I don't see a reason not to use MIT or Apache 2.0 licenses. They are the default choices in all Rust projects. If you are using Bevy, you already have to comply with these licenses and also with all the licenses on which Bevy depends. So changing the licenses to be public domain or CC-0 doesn't change much.

**Comment by ameknite** [comment]
Additionally, with MIT and Apache 2.0 licenses, both permit relicensing . They are not copyleft licenses, so you only need to comply with the license you select. In the case of MIT, include the notice and the license, and with Apache, it's almost the same; just ensure you clearly indicate that you are changing the license and that the original template was licensed under Apache 2.0.

**Comment by ameknite** [comment]
Creative Commons does not recommend using their licenses for software: 
https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

Public domain isn’t recognised everywhere (like Germany):
https://news.ycombinator.com/item?id=29025058

MIT and Apache2.0 avoid you problems like:

- Liability
- Warranty
- Patent use

**Comment by lizelive** [comment]
> Creative Commons does not recommend using their licenses for software: https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

CC0 is exception

https://wiki.creativecommons.org/wiki/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F

You can triple licence it.

**Comment by ameknite** [comment]
@lizelive You're right, I think the best solution would be triple licensing (CC0/MIT/Apache 2.0). It let the user choose which license to comply with

**Comment by ameknite** [comment]
I updated this PR to also include the CC0-1.0 license so the user can choose the license they prefer to comply

**Review by alice-i-cecile — APPROVED** [review]

**Review by mockersf — APPROVED** [review]

**Comment by mockersf** [comment]
my only issue is that most people will use the template to create a new project and then not care much about the license... but that's an issue with how GitHub templates handle licenses. until we have a tool to create a project from scratch or a template and decide on the license at creation time, this is the best we can do I guess

**Comment by ickk** [comment]
We need all the contributors to this repository to actually agree to re-license their contributions under this new license! This should not have been done unilaterally and isn't currently valid

See https://github.com/bevyengine/bevy/issues/2373 for an example of how this can be done

**Comment by cart** [comment]
Agreed. Good call @ickk. This not have been done and given that we've properly gone through this process in the past, we had a template for the proper approach. This was a miss that we should learn from.

Fortunately in this case there are very few people to track down. Additionally, most of the changes do not constitute "non-trivial intellectual property". We _might_ have been able to get away with this legally (I am not a lawyer). That being said,  we _should_ do the right thing here, and avoid doing the wrong thing in the future.

Taking the approvals on this PR as consent, can the remaining people please respond with the following boilerplate (if you agree to relicense your contributions):

> I license past and future contributions to this repo under the triple MIT/Apache-2.0/CC-0 license, allowing licensees to choose any at their option.

* @idanarye 
* @paul-hansen 
* @marlyx 
* @archblob 
* @rowanfr 
* @hymm
* @rparrett
* @NiklasEi 
* @neosam

**Comment by hymm** [comment]
I license past and future contributions to this repo under the triple MIT/Apache-2.0/CC-0 license, allowing licensees to choose any at their option.

**Comment by rowanfr** [comment]
I license past and future contributions to this repo under the triple MIT/Apache-2.0/CC-0 license, allowing licensees to choose any at their option.

**Comment by rparrett** [comment]
I license past and future contributions to this repo under the triple MIT/Apache-2.0/CC-0 license, allowing licensees to choose any at their option.

**Comment by idanarye** [comment]
I license past and future contributions to this repo under the triple MIT/Apache-2.0/CC-0 license, allowing licensees to choose any at their option.

**Comment by DGriffin91** [comment]
> I license past and future contributions to this repo under the triple MIT/Apache-2.0/CC-0 license, allowing licensees to choose any at their option.

@cart Does this statement mean that the included Bevy logo is now public domain?

**Comment by paul-hansen** [comment]
I license past and future contributions to this repo under the triple MIT/Apache-2.0/CC-0 license, allowing licensees to choose any at their option.

**Comment by neosam** [comment]
I license past and future contributions to this repo under the triple MIT/Apache-2.0/CC-0 license, allowing licensees to choose any at their option.

**Comment by claudijo** [comment]
I license past and future contributions to this repo under the triple MIT/Apache-2.0/CC-0 license, allowing licensees to choose any at their option.

**Comment by cart** [comment]
I'm checking the @archblob box because a single version number bump is definitely "trivial".

**Comment by cart** [comment]
With that, we're done!

**Pull request merged**
